# Generated by Django 5.1 on 2025-03-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSPAN_data',
        ),
    ]
